// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw14FD0Bdr_SI-e1iREpf9WeQ3ux49QCk',
    appId: '1:596231402827:web:de170fdd0d9f13cdb3e4ce',
    messagingSenderId: '596231402827',
    projectId: 'recipie-app-8c9eb',
    authDomain: 'recipie-app-8c9eb.firebaseapp.com',
    storageBucket: 'recipie-app-8c9eb.appspot.com',
    measurementId: 'G-GBJVFTB3RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuWnQucJQCdXPzUy0niaUoNjxzOhUSKrs',
    appId: '1:596231402827:android:ea0360009ac6fa1db3e4ce',
    messagingSenderId: '596231402827',
    projectId: 'recipie-app-8c9eb',
    storageBucket: 'recipie-app-8c9eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY3tzBQ_cKq9VOtdUyT0Kjf7ykYhW-xfE',
    appId: '1:596231402827:ios:87a109521901946cb3e4ce',
    messagingSenderId: '596231402827',
    projectId: 'recipie-app-8c9eb',
    storageBucket: 'recipie-app-8c9eb.appspot.com',
    iosBundleId: 'com.example.recipieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY3tzBQ_cKq9VOtdUyT0Kjf7ykYhW-xfE',
    appId: '1:596231402827:ios:87a109521901946cb3e4ce',
    messagingSenderId: '596231402827',
    projectId: 'recipie-app-8c9eb',
    storageBucket: 'recipie-app-8c9eb.appspot.com',
    iosBundleId: 'com.example.recipieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw14FD0Bdr_SI-e1iREpf9WeQ3ux49QCk',
    appId: '1:596231402827:web:a120a9ea345bbe3bb3e4ce',
    messagingSenderId: '596231402827',
    projectId: 'recipie-app-8c9eb',
    authDomain: 'recipie-app-8c9eb.firebaseapp.com',
    storageBucket: 'recipie-app-8c9eb.appspot.com',
    measurementId: 'G-L3VPVGE2DV',
  );

}